### ISSUE TITLE
Build fails with newer JDK releases

### ISSUE THREAD

**Issue by bmihaila** [blackducksoftware/bdio#7]
Hi

It seems that some of the BDIO library dependencies pulls in some JDK 8 or 9 specific code which breaks on compilation with newer JDKs, i.e. 10, 11, 12 
Trying to compile with JDK 11, 12 below gives this error:
```
All input files are considered out-of-date for incremental task ':bdio2:compileJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with error-prone compiler
/Users/.../devel/bdio-libraries/bdio2/src/main/java/com/blackducksoftware/bdio2/NodeDoesNotExistException.java:18: error: cannot access Objects
import java.util.Objects;
                ^
  bad class file: /modules/java.base/java/util/Objects.class
    class file has wrong version 56.0, should be 53.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
1 error
:bdio2:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 0.795 secs.
```
As those JDKs have been phased out of support year(s) ago it would be nice to update the build and make it compatible with more recent Java versions.

Thanks
Bogdan

**Comment by sig-daveka** [comment]
I think it's maybe the other way around?  Having version 56.0 means it found a Java 12 class file, "should be 53.0" means that it needed Java 9.

**Comment by bmihaila** [comment]
hmm... not the other way round. The project is compiled with my JDK 12 and during the compilation some transitive dependency that contained jdk9 in the jarname (need to reproduce again to find the full name) tries to link against those JDK 12 class files and fails.

So proper fix is to update that dependency. You can reproduce above by installing JDK11 or 12 and doing a clean gradle build like this:
```
gradle clean
gradle build --no-build-cache
```

**Comment by bmihaila** [comment]
Ok I tried to reproduce again. So `rm -r ~/.gradle; gradle --no-build-cache --info build -x test`

Things go fine until this dep gets downloaded:
`javac-9+181-r4173-1.jar` in this process:

```
Downloading https://jcenter.bintray.com/com/google/errorprone/error_prone_core/2.3.3/error_prone_core-2.3.3.jar to /private/var/folders/xw/8zscmtgx3fx9lwhjnz7jt_cw0000gn/T/gradle_download4953590045505959704bin
Downloading https://jcenter.bintray.com/org/checkerframework/dataflow/2.5.3/dataflow-2.5.3.jar to /private/var/folders/xw/8zscmtgx3fx9lwhjnz7jt_cw0000gn/T/gradle_download9240986710296202057bin
Downloading https://jcenter.bintray.com/com/google/errorprone/error_prone_annotations/2.3.3/error_prone_annotations-2.3.3.jar to /private/var/folders/xw/8zscmtgx3fx9lwhjnz7jt_cw0000gn/T/gradle_download8133871257524946345bin
Downloading https://jcenter.bintray.com/com/google/errorprone/javac/9+181-r4173-1/javac-9+181-r4173-1.jar to /private/var/folders/xw/8zscmtgx3fx9lwhjnz7jt_cw0000gn/T/gradle_download17919877673661008780bin
```

Judging from above jar and this https://stackoverflow.com/a/30079028 it seems that the error happens due to this `error-prone` dependency pulling in its own Javac9 compiler and using that to compile some of the classes. Later on linking those together with the rest of the build fails :P.

So solution is to update or get rid of that dependency as it uses a hardcoded JDK compiler.

**Comment by bd-skatzman** [comment]
Errorprone as documented only supports JDK9 and above.  There are hacks to allow it to work with JDK8.   The dependency has been removed for the time being.   I think, long-term, the project should be updated to work with the current Java LTS release (currently 11) and static analysis tools should be evaluated for use.
